import { tokens } from "./tokens";
import { tokenKeyToCssVar, sidebarKeyToCssVar } from "./utils";
import * as fs from "fs";
import * as path from "path";

const globalsPath = path.join(process.cwd(), "app", "globals.css");

function generateRootBlock(): string {
  const lines: string[] = ["  /* Design tokens — generated by npm run tokens */"];

  // Colors
  for (const [key, value] of Object.entries(tokens.colors)) {
    lines.push(`  ${tokenKeyToCssVar(key)}: ${value};`);
  }

  // Radius
  lines.push(`  --radius: ${tokens.radius};`);

  // Sidebar colors
  for (const [key, value] of Object.entries(tokens.sidebar)) {
    lines.push(`  ${sidebarKeyToCssVar(key)}: ${value};`);
  }

  return `:root {\n${lines.join("\n")}\n}`;
}

const isCheck = process.argv.includes("--check");
const rootBlock = generateRootBlock();

if (isCheck) {
  const current = fs.readFileSync(globalsPath, "utf8");
  const hasBlock = current.includes("/* Design tokens — generated by npm run tokens */");
  if (!hasBlock) {
    console.error("globals.css is out of sync. Run: npm run tokens");
    process.exit(1);
  }
  console.log("✅ Design tokens are in sync.");
} else {
  let css = "";
  if (fs.existsSync(globalsPath)) {
    const current = fs.readFileSync(globalsPath, "utf8");
    // Replace existing :root block or prepend
    const rootRegex = /:root\s*\{[^}]*\/\* Design tokens[^}]*\}/s;
    if (rootRegex.test(current)) {
      css = current.replace(rootRegex, rootBlock);
    } else {
      css = rootBlock + "\n\n" + current;
    }
  } else {
    css = rootBlock;
  }
  fs.writeFileSync(globalsPath, css);
  console.log("✅ globals.css updated with design tokens.");
}
